descriptions = new Array("Welcome to Feed Editor Top Next ExtraLabs Software unveils Feed Editor, a fully-fledged RSS editor that offers you an easy way to create and maint...",
	"Purchasing Top Previous Next Feed Editor can be purchased via the Internet, Phone, Mail, via Fax, Purchase Order, PayPal, by Check, Cash, or Bank/...",
	"End User License Agreement Top Previous Next END-USER LICENSE AGREEMENT FOR FEED EDITOR IMPORTANT: PLEASE READ THE TERMS AND CONDITIONS OF THIS LI...",
	"Where to Get Help Top Previous Next There are several resources that can help you with using Feed Editor. This manual is just one of them. Website...",
	"Userful links Top Previous Next Especially for you we have prepared a collection of links that will help a novice to master the RSS and podcasting...",
	"Contact Us Top Previous Next Feed Editor is developed by ExtraLabs Software. Contact Information: Email Addresses sales@extralabs.net support@extr...",
	"New Feed Wizard Top Previous Next The simplest way to create a new RSS feed is to use the New Feed Wizard. When the program is launched first time...",
	"Main window Top Previous Next The main window of the program can be divided into several main areas. Menu The program is controlled using the menu...",
	"Feed Tab Top Previous Next The \"Feed\" tab if active if there is an opened RSS feed. Using this tab you can access the main (title, description, li...",
	"Image Tab Top Previous Next When the “Image” tab is active, you have access to the feed image. It is not necessary for an RSS feed to have an imag...",
	"Creating New Feed Top Previous Next To get a new feed, you can use one of the following: • Create a blank feed. Click the “New Feed” button in the...",
	"Opening Existing Feed Top Previous Next To open an existing RSS feed, press the “Open Feed” button in the Feed toolbar or select the “Open…” butto...",
	"Editing Feed Top Previous Next The current feed can be easily edited by changing the field values in the Editing Areas of the Feed Editor main win...",
	"Saving Feed Top Previous Next After you have created an RSS feed or edited it, it should be saved. The file is stored on your local drive. To save...",
	"Uploading Feed Top Previous Next Feed Editor allows you to upload your RSS feed to a server using the built-in FTP-client. To invoke its window, c...",
	"Removing Feed Top Previous Next To remove the current RSS feed, press the “Remove Feed” button or select the “Remove” item of the “Feed” menu. The...",
	"Creating New Item Top Previous Next To create a new item of your RSS feed, press the “Create Item” button in the Item toolbar, or select the “New”...",
	"Editing Item Top Previous Next The current feed item can be easily edited by changing the field values in the Editing Area of the “Feed Items” tab...",
	"Cloning Item Top Previous Next Sometimes it is convenient to use data from an existing item to create a new item of your RSS feed. That is way thi...",
	"Deleting Item Top Previous Next To delete the current item of your RSS feed, press the “Remove Item” button in the Item toolbar or select the “Rem...",
	"Rearranging Item Order Top Previous Next For most news readers, the order in which the items are displayed is the order in which you have them in ...",
	"Including Image in Feed Top Previous Next Adding an image to your RSS feed can give it a more professional look. As defined in the RSS specificati...",
	"Using HTML in Description Fields Top Previous Next The RSS specification permits using HTML tags in description fields. Feed Editor features the b...",
	"Overview Top Previous Next When creating an RSS feed, you can enter all necessary data either manually or in the half-automatic mode using the Imp...",
	"Using Import Wizard Top Previous Next You can import data to the current RSS feed from HTML, CSV and XML files. The importing process consists of ...",
	"Overview Top Previous Next Feed Editor provides powerful yet easy-to-use exporting functionality: templates are used for determining the output fi...",
	"Templates Top Previous Next Export templates are simple text files that contains special variables as well as the formatted text. Use these variab...",
	"Using Export Feature Top Previous Next To export data from the current RSS feed, open the export window, select a template and the path to the out...",
	"Using the Source Code Editor Top Previous Next Feed Editor features the built-in XML editor that can be used if you want to edit the RSS code manu...",
	"Using the Preview Feature Top Previous Next In Feed Editor, you can always find out how your feed will look in RSS readers even before it is publi...",
	"Program settings Top Previous Next The Feed Editor preferences window will help you configure the program in the most convenient way. To invoke th...",
	"Converting RSS to HTML online: Feed2Html Top Previous Next Starting with version 3.6, a free PHP-script is provided with Feed Editor, which can be...",
	"Templates Top Previous Next The feed2html.php script bundled with Feed Editor uses templates to generate its output. The templates allow you to ea...",
	"Launching script Top Previous Next Before using the script, it should be properly configured. This can be done in one of the following two ways: M...",
	"Recommended software Top Previous Feed Mix makes anyone an RSS feed mix DJ It lets you create, edit and publish the unlimited number of RSS feeds ...");