titles = new Array("Welcome to Feed Editor",
	"Purchasing",
	"End User License Agreement",
	"Where to Get Help",
	"Userful links",
	"Contact Us",
	"New Feed Wizard",
	"Main window",
	"Feed Tab",
	"Image Tab",
	"Creating New Feed",
	"Opening Existing Feed",
	"Editing Feed",
	"Saving Feed",
	"Uploading Feed",
	"Removing Feed",
	"Creating New Item",
	"Editing Item",
	"Cloning Item",
	"Deleting Item",
	"Rearranging Item Order",
	"Including Image in Feed",
	"Using HTML in Description Fields",
	"Overview",
	"Using Import Wizard",
	"Overview",
	"Templates",
	"Using Export Feature",
	"Using the Source Code Editor",
	"Using the Preview Feature",
	"Program settings",
	"Converting RSS to HTML online: Feed2Html",
	"Templates",
	"Launching script",
	"Recommended software");